language: cpp
notifications:
  email: false
os: linux
dist: trusty
jobs:
  include:
    - name: "macOS Clang 9.1"
      os: osx
      osx_image: xcode9.4
    - name: "macOS Clang 10.0"
      os: osx
      osx_image: xcode10.1
    - name: "macOS Clang 11.0"
      os: osx
      osx_image: xcode11.2
    #TODO: Add support for Linux Clang Compilers
    - name: "Linux GCC 5 C++14"
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
      addons:
        apt:
          packages: g++-5
          sources:
            - ubuntu-toolchain-r-test
    - name: "Linux GCC 6 C++14"
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
      addons:
        apt:
          packages: g++-6
          sources:
            - ubuntu-toolchain-r-test
    - name: "Linux GCC 7 C++14"
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      addons:
        apt:
          packages: g++-7
          sources:
            - ubuntu-toolchain-r-test
    - name: "Linux GCC 8 C++14"
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
      addons:
        apt:
          packages: g++-8
          sources:
            - ubuntu-toolchain-r-test
    - name: "Windows MSVC 2017"
      os: windows
before_install:
  - eval "${MATRIX_EVAL}"
install:
  - |-
      case $TRAVIS_OS_NAME in
        linux)
          DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
          mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
          travis_retry wget --no-check-certificate https://www.cmake.org/files/v3.14/cmake-3.14.0-Linux-x86_64.tar.gz
          tar -xvf cmake-3.14.0-Linux-x86_64.tar.gz > /dev/null
          mv cmake-3.14.0-Linux-x86_64 cmake-install
          PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
          cd ${TRAVIS_BUILD_DIR}
          ;;
      esac
script:
  - cmake --version
  - cmake -P cmake/cpplint.cmake
  - |-
      case $TRAVIS_OS_NAME in
        osx|linux)
          cmake -B build
          cmake --build build
          ;;
        windows)
          cmake -B build -A x64
          cmake --build build --config Release
          ;;
      esac