sudo: false
language: cpp
compiler:
  - gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.8
    - george-edison55-precise-backports
    packages:
    - g++-6
    - clang-3.8
    - cmake-data
    - cmake
before_install:
  - wget https://raw.githubusercontent.com/cpplint/cpplint/master/cpplint.py
script:
  - ./scripts.sh lintci
  - ./scripts.sh install
  - ./scripts.sh build