name: ci-build-windows

on:
  push:
    branches:
      - master
    paths-ignore:
      - .dockerignore
      - .gitignore
      - .gitattributes
      - AUTHORS
      - CONTRIBUTING.md
      - docker-compose.yml
      - LICENSE
      - README.md
      - Dockerfile
      - images/*
      - docker/*
  pull_request:

jobs:
  build-windows:
    name: "Windows MSVC 2025"
    runs-on: windows-2025
    steps:
    - name: Checkout
      uses: actions/checkout@v7
    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.28.6'
    - name: Cpplint
      run: cmake -P cmake/cpplint.cmake
    - name: Configure
      run: cmake -B build -A x64 -D DOWNLOAD_DATASETS=OFF
    - name: Build tutorials
      run: cmake --build build --config Release --parallel 4
