name: ci-build-macos

on:
  push:
    paths-ignore:
      - .dockerignore
      - .gitignore
      - .gitattributes
      - AUTHORS
      - CONTRIBUTING.md
      - docker-compose.yml
      - LICENSE
      - README.md
      - Dockerfile
      - images/*
      - docker/*
  pull_request:

jobs:
  build-mac:
    name: "macOS 14.4.1 arm64 Xcode (Clang)"
    runs-on: macos-14
    strategy:
      matrix:
        xcode: [14.3.1, 15.3]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.19.0'
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ matrix.xcode }}
    - name: Cpplint
      run: cmake -P cmake/cpplint.cmake
    - name: Configure
      run: cmake -B build -D DOWNLOAD_DATASETS=OFF
    - name: Build tutorials
      run: cmake --build build --parallel 4
